More contacts on the page
osm-ua/openstreetmap.org.ua pull request #27
Opened 2021-08-12 19:48 UTC by Kilkenni

Updated FontAwesome to v5
Added contact: Telegram channel
Added contact: Slack
Replaced icon for "To top" button

2021-08-13 15:07 UTC, Andygol requested changes
Я переглянув код, є незначні зауваження які треба виправити.

2021-08-13 15:07 UTC, Andygol commented on _includes/footer.html
> +            <a href="#"><i class="fas fa-arrow-circle-up fa-fw fa-3x"></i></a> <!-- previously used fab fa-dribbble-->
Що на рахунок замінити іконку на `<i class="fas fa-globe-europe"></i>`?

Див - https://fontawesome.com/v5.15/icons/globe-europe?style=solid

2021-08-13 15:07 UTC, Andygol commented on _includes/footer.html
> +            <a href="https://t.me/osmUA/{{ site.telegram_username }}"><i class="fab fa-telegram fa-fw fa-3x"></i></a>
З посилання треба прибрати `osmUA` 
```suggestion
            <a href="https://t.me/{{ site.telegram_username }}"><i class="fab fa-telegram fa-fw fa-3x"></i></a>
```

2021-08-13 15:07 UTC, Andygol commented on _includes/footer.html
> +            <a href="https://osmukraine.slack.com/{{ site.slack_username }}"><i class="fab fa-slack fa-fw fa-3x"></i></a>
Треба винести `{{ site.slack_username }}` з href="…" через формування некоректного посилання.  `osmukraine.slack.com` краще замінити на переадресацію на посилання-запрошення через `bit.ly`

```suggestion
            <a href="https://bit.ly/SlackOsmUa/" title="{{ site.slack_username }}"><i class="fab fa-slack fa-fw fa-3x"></i></a>
```

2021-08-13 15:11 UTC, Andygol commented
Через оновлення шрифту зникла одна з іконок, потрібно додати нову
![image](https://user-images.githubusercontent.com/369696/129378934-6446421c-c89e-4634-835e-a0163cf2038f.png)

2021-08-16 22:32 UTC, Kilkenni commented
> Через оновлення шрифту зникла одна з іконок, потрібно додати нову `<i class="fas fa-shield-alt"></i>`
> 
> https://fontawesome.com/v5.15/icons/shield-alt?style=solid
> 
> ![image](https://user-images.githubusercontent.com/369696/129378934-6446421c-c89e-4634-835e-a0163cf2038f.png)

Зробив.

2021-08-16 22:41 UTC, Kilkenni commented on _includes/footer.html
> +            <a href="#"><i class="fas fa-arrow-circle-up fa-fw fa-3x"></i></a> <!-- previously used fab fa-dribbble-->
Зробив.
Щоправда, я не дуже розумію, навіщо взагалі на односторінковому сайті посилання на сам сайт... ну та йой, най буде. Мені не заважає.

2021-08-16 22:49 UTC, Kilkenni commented on _includes/footer.html
> +            <a href="https://osmukraine.slack.com/{{ site.slack_username }}"><i class="fab fa-slack fa-fw fa-3x"></i></a>
Можна, тільки без слеша в кінці: "https://bit.ly/SlackOsmUa". Зі слешем викидає на 404.
А чому краще через bit.ly, поясни, будь ласка? Я зазвичай не люблю ставити на сайт довготривалі посилання через скорочувач - відвідувач може ставитися до такого з підозрою (принаймні, я так ставлюся).

2021-08-17 17:17 UTC, merged

2021-08-17 17:17 UTC, Andygol commented
Дякую, виглядає добре.